#! /bin/sh
#curl http://169.254.169.254/latest/meta-data/public-hostname
DAVS=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname)
sed -i s/tcp:.*:/tcp:$DAVS:/g CICSDB1.xml
mfds -g 5 $PWD/CICSDB1.xml
sed -i s/tcp:.*:/tcp:$DAVS:/g CICSDB2.xml
mfds -g 5 $PWD/CICSDB2.xml


